version: "3.8"
services:
  postgres:
    container_name: postgres_Bookstore
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Bookstore
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_Bookstore
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dabshite8@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
